version: '3'
services:
  nginx:
    image: 'nginx:alpine'
    ports:
      - '80:80'
    volumes:
      - '/Users/jonerickson/Documents/Invision Community/4.7.0:/var/www/html' # Edit For Your Local Environment
      - './data/:/var/www/html/applications/netgsm/data'
      - './dev/:/var/www/html/applications/netgsm/dev'
      - './extensions/:/var/www/html/applications/netgsm/extensions'
      - './hooks/:/var/www/html/applications/netgsm/hooks'
      - './interface/:/var/www/html/applications/netgsm/interface'
      - './modules/:/var/www/html/applications/netgsm/modules'
      - './setup/:/var/www/html/applications/netgsm/setup'
      - './sources:/var/www/html/applications/netgsm/sources'
      - './tasks/:/var/www/html/applications/netgsm/tasks'
      - './Application.php:/var/www/html/applications/netgsm/Application.php'
      - './nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf'
    networks:
      - netgsm
    depends_on:
      - php
      - mysql
      - redis
      - mailhog
  php:
    build:
      context: ./docker/8.0
      dockerfile: Dockerfile
    image: invision-8.0/app
    volumes:
      - '/Users/jonerickson/Documents/Invision Community/4.7.0:/var/www/html' # Edit For Your Local Environment
      - './data/:/var/www/html/applications/netgsm/data'
      - './dev/:/var/www/html/applications/netgsm/dev'
      - './extensions/:/var/www/html/applications/netgsm/extensions'
      - './hooks/:/var/www/html/applications/netgsm/hooks'
      - './interface/:/var/www/html/applications/netgsm/interface'
      - './modules/:/var/www/html/applications/netgsm/modules'
      - './setup/:/var/www/html/applications/netgsm/setup'
      - './sources:/var/www/html/applications/netgsm/sources'
      - './tasks/:/var/www/html/applications/netgsm/tasks'
      - './Application.php:/var/www/html/applications/netgsm/Application.php'
      - './php/conf.d/php.ini:/usr/local/etc/php/conf.d/100-custom.ini'
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - netgsm
  mysql:
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_DATABASE: '${DB_DATABASE:-invision-4.7.0}'
      MYSQL_USER: '${DB_USERNAME:-invision}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mysql:/var/lib/mysql'
    networks:
      - netgsm
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-password}"]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    networks:
      - netgsm
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - netgsm
networks:
  netgsm:
    driver: bridge
volumes:
  mysql:
    driver: local
  redis:
    driver: local
