<ips:template parameters="$form" />
{{if !request.isAjax()}}
	{template="pageHeader" group="global" params="\IPS\Member::loggedIn()->language()->addToStack('lost_password')"}
{{endif}}
<div class='ipsBox ipsPadding'>
	{$form|raw}
	<hr class="ipsHr" />
	<div class="ipsSpacer_top">
    <a href='{url="app=core&module=system&controller=lostpass&use=email" seoTemplate="lostpassword" base="front"}' class="ipsType_neutral">
    	{lang="netgsm_lost_password_email"}
    </a>
	</div>
</div>
